print("Hola Mundo Buenas Tardes")
print("Como estan Señores y Señoras?")
print("Que Cuentas Tienen?")
print("Gracias, Hasta Luego")
print("Adios, Nos Vemos Mañana")
print("Hasta Luego, Nos Vemos Mañana")