a = int(input("Ingrese un número: "))
b = int(input("Ingrese otro número: "))
print("La suma es:", a + b)
c = int(input("Ingrese un tercer número: "))
print("La suma de los tres números es:", a + b + c)
d = int(input("Ingrese un cuarto número: "))
print("La suma de los cuatro números es:", a + b + c + d)
e = int(input("Ingrese un quinto número: "))
print("La suma de los cinco números es:", a + b + c + d + e)
f = int(input("Ingrese un sexto número: "))
print("La suma de los seis números es:", a + b + c + d + e)
g = int(input("Ingrese un séptimo número: "))
print("La suma de los siete números es:", a + b + c + d + e + f + g)
h = int(input("Ingrese un octavo número: "))
print("La suma de los ocho números es:", a + b + c + d + e)
i = int(input("Ingrese un noveno número: "))
print("La suma de los nueve números es:", a + b + c + d + e)
j = int(input("Ingrese un décimo número: "))
print("La suma de los diez números es:", a + b + c + d + e)
