a = int(input("Ingrese un número: "))
b = int(input("Ingrese otro número: "))
print("La suma es:", a + b)
c = int(input("Ingrese un tercer número: "))
print("La suma de los tres números es:", a + b + c)
d = int(input("Ingrese un cuarto número: "))
print("La suma de los cuatro números es:", a + b + c + d)